# docker-compose.yml
version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: produtos-db-mysql
    environment:
      MYSQL_DATABASE: produtos_db
      MYSQL_USER: quarkus
      MYSQL_PASSWORD: quarkus
      MYSQL_ROOT_PASSWORD: root # Senha para o usuário root do MySQL
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: