quarkus.datasource.db-kind=mysql

# Configuração do Hibernate ORM (JPA)
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true

# (opcional) Personalizações do DevServices
# Imagem Docker do MySQL
quarkus.datasource.devservices.image-name=mysql:8.0

# Nome do banco criado automaticamente
quarkus.datasource.devservices.database-name=meu_banco

# Usuário e senha
quarkus.datasource.devservices.username=quarkus
quarkus.datasource.devservices.password=quarkus

# Nome fixo do container (facilita no debug)
quarkus.datasource.devservices.container-name=meu-mysql-dev