
#  Configuração do banco de dados (MySQL via Dev Services)
quarkus.datasource.db-kind=mysql
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true

#  Configuração do Keycloak (OIDC)

quarkus.oidc.client-id=backend-service
quarkus.oidc.credentials.secret=Nrm0RGqro1Eb9YWgIGuZjp9fpFTOwTOg
quarkus.oidc.application-type=service
quarkus.oidc.auth-server-url=http://localhost:8081/realms/quarkus
# Desabilitar Dev Services para Keycloak
quarkus.keycloak.devservices.enabled=false

